<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"> 
       >
  <xacro:property name="safety_offset" value="0.02"/>

  <xacro:include filename="$(find description_lwa4p)/urdf/lwa4p/lwa4p.gazebo.xacro" />
  <xacro:include filename="$(find description_lwa4p)/urdf/lwa4p/lwa4p.transmission.xacro" />
  

  <xacro:macro name="schunk_lwa4p" params="parent name *origin has_podest tool_point" >

    <xacro:if value="${has_podest}">
      <!-- joint between base_link and lwa4p_extended_connector_link -->
      <joint name="${name}_podest_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_podest_link"/>
      </joint>
      
      <link name="${name}_podest_link">
        <xacro:default_inertial/>
        <visual>
          <origin xyz="0 0 0" rpy="${M_PI/2} 0 -${M_PI/2}" />
          <geometry>
          <mesh filename="package://description_lwa4p/meshes/visual/arm_base_link.stl"  scale = "0.001 0.001 0.001"/>
          </geometry>
	  <material name="Schunk/DarkGrey"/>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="${M_PI/2} 0 -${M_PI/2}"  />
          <geometry>
	    <mesh filename="package://description_lwa4p/meshes/collision/arm_base_link_collision.stl"  scale = "0.0011 0.0011 0.0011"/> <!-- <cylinder length="0.140" radius = "${0.187/2}"/>  data from documentation simple shape for better collision planning -->
          </geometry>
        </collision>
      </link>

      <joint name="${name}_base_joint" type="fixed">
        <origin xyz="0 0 ${0.2053 - 0.070}" rpy="0 0 0" />
        <parent link="${name}_podest_link"/>
        <child link="${name}_base_link"/>
      </joint>
      
      <gazebo reference="${name}_podest_link">
	  <gravity>true</gravity>
	  <self_collide>false</self_collide>
	  <material>Gazebo/Grey</material>
      </gazebo>
      
    </xacro:if>

    <xacro:unless value="${has_podest}">
      <!-- joint between base_link and lwa4p_extended_connector_link -->
      <joint name="${name}_base_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_base_link"/>
      </joint>
    </xacro:unless>

    <link name="${name}_base_link">
      <xacro:default_inertial/>
    </link>

    <!-- joint between arm_0_link and arm_1_link -->
    <joint name="${name}_1_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${name}_base_link"/>
      <child link="${name}_1_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="370" velocity="0.4" lower="${-2.9}" upper="${2.9}"/>
      <!--<limit effort="370" velocity="2.0" lower="${-6.28 + safety_offset}" upper="${6.28 - safety_offset}"/>-->
      <safety_controller k_position="20" k_velocity="50" soft_lower_limit="${-2.9 + 0.01}" soft_upper_limit="${2.9 - 0.01}" />
    </joint>

    <link name="${name}_1_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.29364"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/visual/arm_joint1_link.stl"  scale = "0.001 0.001 0.001" />
        </geometry>
        <material name="Schunk/DarkGrey"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
           <mesh filename="package://description_lwa4p/meshes/collision/arm_joint1_link_collision.stl"  scale = "0.0011 0.0011 0.0011" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_1_link and arm_2_link -->
    <joint name="${name}_2_joint" type="revolute">
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <parent link="${name}_1_link"/>
      <child link="${name}_2_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="370" velocity="0.4" lower="${-2}" upper="${2}"/> <!-- changed Miroslav Kohut from 1.4 to 2 -->>
      <safety_controller k_position="20" k_velocity="50" soft_lower_limit="${-2.0 + 0.01}" soft_upper_limit="${2.0 - 0.01}" />
    </joint>

    <link name="${name}_2_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.68311"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/visual/arm_1_link.dae" />
        </geometry>
        <material name="Schunk/Blue"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/visual/arm_1_link.stl" scale = "1.05 1.05 1.05"/>
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_2_link and arm_3_link -->
    <joint name="${name}_3_joint" type="revolute">
      <origin xyz="0 0.350 0" rpy="0 3.14159 0"/>
      <parent link="${name}_2_link"/>
      <child link="${name}_3_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="176" velocity="0.4" lower="${-2.6}" upper="${2.6}"/>
      <safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.6 + 0.01}" soft_upper_limit="${2.6 - 0.01}" />
    </joint>

    <link name="${name}_3_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.1"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/visual/arm_joint1_link.stl"  scale = "0.001 0.001 0.001" />
        </geometry>
        <material name="Schunk/DarkGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/collision/arm_joint1_link_collision.stl"  scale = "0.0011 0.0011 0.0011" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_3_link and arm_4_link -->
    <joint name="${name}_4_joint" type="revolute">
      <origin xyz="0 0 0" rpy="-1.5708 3.14159 0" />
      <parent link="${name}_3_link"/>
      <child link="${name}_4_link"/>
      <axis xyz="0 0 1" />
      <limit effort="176" velocity="0.4" lower="${-2.9}" upper="${2.9}"/>
      <!--<limit effort="176" velocity="2.0" lower="${-6.28 + safety_offset}" upper="${6.28 - safety_offset}"/> -->
      <safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.9 + 0.01}" soft_upper_limit="${2.9 - 0.01}" />
    </joint>

    <link name="${name}_4_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.68311"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/visual/arm_2_link.dae" />
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/visual/arm_2_link.stl" scale = "1.03 1.03 1.03" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_4_link and arm_5_link -->
    <joint name="${name}_5_joint" type="revolute">
      <origin xyz="0 0 0.3049" rpy="1.5708 0 3.14159" />
      <parent link="${name}_4_link"/>
      <child link="${name}_5_link"/>
      <axis xyz="0 0 1" />
      <limit effort="41.6" velocity="0.4" lower="${-2.9}" upper="${2.9}" />
      <!--<limit effort="41.6" velocity="2.0" lower="${-6.28 + safety_offset}" upper="${6.28 - safety_offset}" /> -->
      <safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.9 + 0.01}" soft_upper_limit="${2.9 - 0.01}" />
    </joint>

    <link name="${name}_5_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.807"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
        <geometry>
	   <mesh filename="package://description_lwa4p/meshes/visual/arm_joint2_link.stl"  scale = "0.001 0.001 0.001" />
        </geometry>
        <material name="Schunk/DarkGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
        <geometry>
           <mesh filename="package://description_lwa4p/meshes/collision/arm_joint2_link_collision.stl"  scale = "0.0011 0.0011 0.0011" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_5_link and arm_6_link -->
    <joint name="${name}_6_joint" type="revolute">
      <origin xyz="0 0 0" rpy="-1.5708 0 0" />
      <parent link="${name}_5_link"/>
      <child link="${name}_6_link"/>
      <axis xyz="0 0 1" />
      <limit effort="20.1" velocity="0.4" lower="${-2.09 }" upper="${2.09}" />
      <safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-2.09 + 0.01}" soft_upper_limit="${2.09 - 0.01}" />
    </joint>

    <link name="${name}_6_link">
      <xacro:default_inertial/>
<!--
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.819"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
-->

      <visual>
        <origin xyz="0 0 0.0460" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/visual/arm_end_link.stl"  scale = "0.001 0.001 0.001" />
        </geometry>
        <material name="Schunk/DarkGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 0.0460" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://description_lwa4p/meshes/collision/arm_end_link_collision.stl"  scale = "0.0011 0.0011 0.0011" />
        </geometry>
      </collision>
      
    </link>
    
    <joint name="${name}_7_joint" type="fixed">
	<origin xyz="0 0 0.0751" rpy="0 0 ${M_PI}" />
	<parent link="${name}_6_link"/>
	<child link="${tool_point}"/>
	<axis xyz="0 0 1" />
    </joint>
    
    <link name ="${tool_point}"/>

    <!-- extensions -->
    <xacro:schunk_lwa4p_gazebo name="${name}" />
    <xacro:schunk_lwa4p_transmission name="${name}" />

  </xacro:macro>

</robot>

